apiVersion: model.youxam.com/v1alpha1
kind: AIModel
metadata:
  name: ai-model-sample
  labels:
    app: ai-model
spec:
  type: local
  model: TinyLlama-1.1B
  replicas: 4
  image: youxam/uplion-aimodel-operator-test-worker:latest
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ai-model-svc
spec:
    selector:
        app: ai-model
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080